let receitas = [], despesas = [], ativos = [], monitorStocks = [], dependentes = [];
let currentUser = null, balancesHidden = false, accessibilityMode = false;
let graficoEvolucao, graficoDespesasCat, graficoDashboardCat;
let speechSynthesisEnabled = false;

const stocksData = { PETR4:38.42, VALE3:62.18, ITUB4:33.75, BBDC4:15.23, ABEV3:12.45, WEGE3:41.92 };
const news = [{title:"Ibovespa sobe com expectativa de cortes de juros"},{title:"Petrobras anuncia novo investimento"},{title:"FIIs rendem 12% ao ano"},{title:"Tesouro Direto novas regras"}];

const chatbotRespostas = {
    "saldo": "Seu saldo atual é a diferença entre receitas e despesas. Veja no topo da tela!",
    "investir": "Para começar a investir, primeiro monte uma reserva de emergência. Depois estude sobre renda fixa e variável.",
    "economizar": "Para economizar, registre todos os gastos, estabeleça um orçamento e evite compras por impulso.",
    "divida": "Priorize quitar dívidas com juros altos como cartão de crédito. Negocie prazos melhores.",
    "padrao": "Posso ajudar com dicas sobre: saldo, investimentos, economia, dívidas, planejamento financeiro. Pergunte algo específico!"
};

function speak(text) { if(speechSynthesisEnabled && 'speechSynthesis' in window) { const utterance = new SpeechSynthesisUtterance(text); utterance.lang = 'pt-BR'; window.speechSynthesis.cancel(); window.speechSynthesis.speak(utterance); document.getElementById("speechBubble").style.display = "block"; document.getElementById("speechBubble").innerHTML = text; setTimeout(()=>{ document.getElementById("speechBubble").style.display = "none"; }, 3000); } }

function chatbotResponder(msg) { const m = msg.toLowerCase(); if(m.includes("saldo")) return chatbotRespostas.saldo; if(m.includes("invest")) return chatbotRespostas.investir; if(m.includes("econom")) return chatbotRespostas.economizar; if(m.includes("divida") || m.includes("dívida")) return chatbotRespostas.divida; return chatbotRespostas.padrao; }

function addMessage(text, isUser) { const container = document.getElementById("chatbotMessages"); const div = document.createElement("div"); div.className = `message ${isUser ? 'user' : 'bot'}`; div.innerHTML = `<div class="message-content">${text}</div>`; container.appendChild(div); container.scrollTop = container.scrollHeight; if(!isUser && accessibilityMode) speak(text); }

function totalReceitas() { return receitas.reduce((a,r)=>a+r.valor,0); }
function totalDespesas() { return despesas.reduce((a,d)=>a+d.valor,0); }
function totalAtivos() { return ativos.reduce((a,i)=>a+(i.quantidade*i.preco),0); }
function saldoAtual() { return totalReceitas() - totalDespesas(); }
function patrimonio() { return saldoAtual() + totalAtivos(); }

function renderAll() {
    document.getElementById("saldoAtual").innerHTML = `R$ ${saldoAtual().toFixed(2)}`;
    document.getElementById("totalReceitas").innerHTML = `R$ ${totalReceitas().toFixed(2)}`;
    document.getElementById("totalDespesas").innerHTML = `R$ ${totalDespesas().toFixed(2)}`;
    document.getElementById("patrimonioTotal").innerHTML = `R$ ${patrimonio().toFixed(2)}`;
    renderAtivos(); renderReceitas(); renderDespesas(); renderDependentes(); renderBalancete('mensal'); renderDashboard();
}

function renderAtivos() { const sections = { renda_fixa:[], acoes:[], fiis:[], cripto:[] }; ativos.forEach(a => { if(sections[a.tipo]) sections[a.tipo].push(a); }); for(let tipo in sections) { const container = document.getElementById(`${tipo}Content`); if(container) { const list = sections[tipo]; if(list.length === 0) container.innerHTML = '<div style="padding:20px;text-align:center;">Nenhum ativo</div>'; else { let html = '<table><thead><tr><th>Ativo</th><th>Qtd</th><th>Preço Médio</th><th>Total</th><th>Ação</th></tr></thead><tbody>'; list.forEach(a => { html += `<tr><td>${a.nome}</td><td>${a.quantidade}</td><td>R$ ${a.preco.toFixed(2)}</td><td>R$ ${(a.quantidade*a.preco).toFixed(2)}</td><td><button class="btn-danger" onclick="removerAtivo(${a.id})"><i class="fas fa-trash"></i></button></td></tr>`; }); html += '</tbody></table>'; container.innerHTML = html; } } } }
window.removerAtivo = (id) => { ativos = ativos.filter(a=>a.id!==id); persistir(); renderAll(); };

function renderStocks() { const c=document.getElementById("stocksList"); if(c){ c.innerHTML='<div style="padding:12px;background:#f3f4f6;border-radius:12px;"><strong>Ibovespa:</strong> 128,432 pts +0.67%</div>'; for(let [sym,price] of Object.entries(stocksData)){ c.innerHTML+=`<div class="stock-monitor-item" style="display:flex;justify-content:space-between;padding:12px;"><div><strong>${sym}</strong></div><div>R$ ${price.toFixed(2)}</div></div>`; } } }
function renderMonitorList() { const c=document.getElementById("monitorList"); if(c){ if(monitorStocks.length===0) c.innerHTML='<div>Adicione ações</div>'; else { let html=''; monitorStocks.forEach((m,idx)=>{ html+=`<div style="display:flex;justify-content:space-between;padding:12px;"><div><strong>${m.symbol}</strong><br><small><a href="${m.link}" target="_blank">Ver cotação</a></small></div><button class="btn-danger" onclick="removerMonitor(${idx})">X</button></div>`; }); c.innerHTML=html; } } }
window.removerMonitor = (idx) => { monitorStocks.splice(idx,1); persistir(); renderMonitorList(); };
function renderNews() { const c=document.getElementById("newsList"); if(c){ c.innerHTML=""; news.forEach(n=>{ c.innerHTML+=`<div style="padding:12px;border-bottom:1px solid #e5e7eb;"><strong>${n.title}</strong></div>`; }); } }
function renderReceitas() { const t=document.querySelector("#tabelaReceitas tbody"); if(t){ t.innerHTML=""; receitas.forEach(r=>{ const row=t.insertRow(); row.insertCell(0).innerText=r.data; row.insertCell(1).innerText=r.desc; row.insertCell(2).innerText=r.categoria; row.insertCell(3).innerHTML=`R$ ${r.valor.toFixed(2)}`; const btn=document.createElement("button"); btn.innerHTML='<i class="fas fa-trash"></i>'; btn.className="btn-danger"; btn.onclick=()=>{ receitas=receitas.filter(x=>x.id!==r.id); persistir(); renderAll(); }; row.insertCell(4).appendChild(btn); }); } }
function renderDespesas() { const t=document.querySelector("#tabelaDespesas tbody"); if(t){ t.innerHTML=""; despesas.forEach(d=>{ const row=t.insertRow(); row.insertCell(0).innerText=d.data; row.insertCell(1).innerText=d.desc; row.insertCell(2).innerText=d.categoria; row.insertCell(3).innerHTML=`R$ ${d.valor.toFixed(2)}`; const btn=document.createElement("button"); btn.innerHTML='<i class="fas fa-trash"></i>'; btn.className="btn-danger"; btn.onclick=()=>{ despesas=despesas.filter(x=>x.id!==d.id); persistir(); renderAll(); }; row.insertCell(4).appendChild(btn); }); } }
function renderDependentes() { const t=document.querySelector("#tabelaDependentes tbody"); if(t){ t.innerHTML=""; dependentes.forEach(d=>{ const row=t.insertRow(); row.insertCell(0).innerText=d.nome; row.insertCell(1).innerText=d.parentesco; row.insertCell(2).innerHTML=`R$ ${d.gastoMensal.toFixed(2)}`; const btn=document.createElement("button"); btn.innerHTML='<i class="fas fa-trash"></i>'; btn.className="btn-danger"; btn.onclick=()=>{ dependentes=dependentes.filter(x=>x.id!==d.id); persistir(); renderAll(); }; row.insertCell(3).appendChild(btn); }); document.getElementById("totalDepGasto").innerHTML=`Total: R$ ${dependentes.reduce((a,d)=>a+d.gastoMensal,0).toFixed(2)}/mês`; } }
function renderDashboard() { const meses=['Jan','Fev','Mar','Abr','Mai','Jun','Jul','Ago','Set','Out','Nov','Dez'], gastos=new Array(12).fill(0), rec=new Array(12).fill(0); despesas.forEach(d=>{ const m=new Date(d.data).getMonth(); gastos[m]+=d.valor; }); receitas.forEach(r=>{ const m=new Date(r.data).getMonth(); rec[m]+=r.valor; }); if(graficoEvolucao) graficoEvolucao.destroy(); const ctx=document.getElementById('graficoEvolucao').getContext('2d'); graficoEvolucao=new Chart(ctx,{ type:'line', data:{ labels:meses, datasets:[{ label:'Receitas', data:rec, borderColor:'#10b981' },{ label:'Despesas', data:gastos, borderColor:'#ef4444' }] }, options:{ responsive:true } }); const cat={}; despesas.forEach(d=>{ cat[d.categoria]=(cat[d.categoria]||0)+d.valor; }); if(graficoDashboardCat) graficoDashboardCat.destroy(); const ctx2=document.getElementById('graficoDashboardCat').getContext('2d'); graficoDashboardCat=new Chart(ctx2,{ type:'doughnut', data:{ labels:Object.keys(cat).slice(0,5), datasets:[{ data:Object.values(cat).slice(0,5), backgroundColor:['#667eea','#764ba2','#f59e0b','#10b981','#ef4444'] }] }, options:{ responsive:true } }); const tb=document.querySelector("#ultimasTransacoes tbody"); if(tb){ tb.innerHTML=""; [...receitas.map(r=>({...r,tipo:"Receita"})),...despesas.map(d=>({...d,tipo:"Despesa"}))].sort((a,b)=>new Date(b.data)-new Date(a.data)).slice(0,6).forEach(item=>{ const row=tb.insertRow(); row.insertCell(0).innerText=item.data; row.insertCell(1).innerText=item.desc; row.insertCell(2).innerText=item.categoria; row.insertCell(3).innerHTML=`<span style="color:${item.tipo==='Receita'?'#10b981':'#ef4444'}">R$ ${item.valor.toFixed(2)}</span>`; }); } }
function renderBalancete(p){ const c=document.getElementById("balanceteContent"); let d={}; if(p==='mensal'){ despesas.forEach(ds=>{ const m=new Date(ds.data).toLocaleString('pt-BR',{month:'long',year:'numeric'}); d[m]=d[m]||{rec:0,desp:0}; d[m].desp+=ds.valor; }); receitas.forEach(r=>{ const m=new Date(r.data).toLocaleString('pt-BR',{month:'long',year:'numeric'}); d[m]=d[m]||{rec:0,desp:0}; d[m].rec+=r.valor; }); } else if(p==='anual'){ despesas.forEach(ds=>{ const a=new Date(ds.data).getFullYear(); d[a]=d[a]||{rec:0,desp:0}; d[a].desp+=ds.valor; }); receitas.forEach(r=>{ const a=new Date(r.data).getFullYear(); d[a]=d[a]||{rec:0,desp:0}; d[a].rec+=r.valor; }); } else d['Total']={rec:totalReceitas(),desp:totalDespesas()}; let html='<div>'; Object.keys(d).sort().forEach(k=>{ const s=d[k].rec-d[k].desp; html+=`<div style="display:flex;justify-content:space-between;padding:12px 0;"><strong>${k}</strong><span>R$ ${d[k].rec.toFixed(2)}</span><span>R$ ${d[k].desp.toFixed(2)}</span><span style="color:${s>=0?'#10b981':'#ef4444'}">R$ ${s.toFixed(2)}</span></div>`; }); html+='</div>'; c.innerHTML=html; }

function toggleBalances() { balancesHidden = !balancesHidden; document.querySelectorAll('.value').forEach(v => { if(balancesHidden) v.classList.add('hidden'); else v.classList.remove('hidden'); }); }

function toggleTheme() { document.body.classList.toggle('dark'); localStorage.setItem('theme', document.body.classList.contains('dark') ? 'dark' : 'light'); }
function toggleAccessibility() { accessibilityMode = !accessibilityMode; document.body.classList.toggle('large-text'); speechSynthesisEnabled = accessibilityMode; if(accessibilityMode) { alert("Modo acessível ativado! Textos maiores e leitura de tela habilitada."); speak("Modo acessível ativado. Agora posso ler as informações para você."); } else { alert("Modo acessível desativado"); } localStorage.setItem('accessibility', accessibilityMode); }

function persistir(){ if(currentUser) localStorage.setItem(`financa_${currentUser.email}`,JSON.stringify({receitas,despesas,ativos,dependentes,monitorStocks})); }
function carregarDados(){ if(currentUser){ const saved=localStorage.getItem(`financa_${currentUser.email}`); if(saved){ const data=JSON.parse(saved); receitas=data.receitas||[]; despesas=data.despesas||[]; ativos=data.ativos||[]; dependentes=data.dependentes||[]; monitorStocks=data.monitorStocks||[]; } } }

document.querySelectorAll(".investment-header").forEach(h=>{ h.addEventListener("click",()=>{ h.nextElementSibling.classList.toggle("active"); }); });
document.getElementById("btnAddAtivo")?.addEventListener("click",()=>{ const tipo=document.getElementById("novoTipo").value, nome=document.getElementById("novoNome").value, qtd=parseFloat(document.getElementById("novoQuantidade").value), preco=parseFloat(document.getElementById("novoPreco").value); if(!nome||isNaN(qtd)||isNaN(preco)) return alert("Preencha todos os campos"); ativos.push({id:Date.now(),tipo,nome,quantidade:qtd,preco}); persistir(); renderAll(); document.getElementById("novoNome").value=""; document.getElementById("novoPreco").value=""; });
document.getElementById("btnAddMonitor")?.addEventListener("click",()=>{ const symbol=document.getElementById("monitorSymbol").value.toUpperCase(); if(!symbol) return; monitorStocks.push({symbol,link:`https://www.google.com/finance/quote/${symbol}:BVMF`}); persistir(); renderMonitorList(); document.getElementById("monitorSymbol").value=""; });
document.getElementById("btnAddReceita")?.addEventListener("click",()=>{ const desc=document.getElementById("recDesc").value, valor=parseFloat(document.getElementById("recValor").value), cat=document.getElementById("recCategoria").value, data=document.getElementById("recData").value||new Date().toISOString().slice(0,10); if(!desc||isNaN(valor)) return alert("Preencha"); receitas.push({id:Date.now(),desc,valor,categoria:cat,data}); persistir(); renderAll(); document.getElementById("recDesc").value=""; document.getElementById("recValor").value=""; });
document.getElementById("btnAddDespesa")?.addEventListener("click",()=>{ const desc=document.getElementById("despDesc").value, valor=parseFloat(document.getElementById("despValor").value), cat=document.getElementById("despCategoria").value, data=document.getElementById("despData").value||new Date().toISOString().slice(0,10); if(!desc||isNaN(valor)) return alert("Preencha"); despesas.push({id:Date.now(),desc,valor,categoria:cat,data}); persistir(); renderAll(); document.getElementById("despDesc").value=""; document.getElementById("despValor").value=""; });
document.getElementById("btnAddDependente")?.addEventListener("click",()=>{ const nome=document.getElementById("depNome").value, parentesco=document.getElementById("depParentesco").value||"Familiar", gasto=parseFloat(document.getElementById("depGasto").value)||0; if(!nome) return; dependentes.push({id:Date.now(),nome,parentesco,gastoMensal:gasto}); persistir(); renderAll(); document.getElementById("depNome").value=""; document.getElementById("depGasto").value=""; });
document.getElementById("btnEnviarContato")?.addEventListener("click",()=>alert("Mensagem enviada!"));
document.getElementById("themeToggle")?.addEventListener("click",toggleTheme);
document.getElementById("accessibilityToggle")?.addEventListener("click",toggleAccessibility);
document.getElementById("toggleBalanceBtn")?.addEventListener("click",toggleBalances);
document.getElementById("chatbotToggle")?.addEventListener("click",()=>document.getElementById("chatbotWindow").classList.toggle("open"));
document.getElementById("chatbotClose")?.addEventListener("click",()=>document.getElementById("chatbotWindow").classList.remove("open"));
document.getElementById("chatbotSend")?.addEventListener("click",()=>{ const input=document.getElementById("chatbotInput"); const msg=input.value.trim(); if(msg){ addMessage(msg,true); setTimeout(()=>{ const resp=chatbotResponder(msg); addMessage(resp,false); },300); input.value=""; } });
document.getElementById("chatbotInput")?.addEventListener("keypress",(e)=>{ if(e.key==="Enter") document.getElementById("chatbotSend").click(); });

document.getElementById("btnLoginSubmit")?.addEventListener("click",()=>{ const email=document.getElementById("loginEmail").value, senha=document.getElementById("loginSenha").value; if(email==="demo@financamaster.com" && senha==="123456"){ currentUser={email,name:"Demo"}; localStorage.setItem("financa_current",JSON.stringify(currentUser)); carregarDados(); document.getElementById("authOverlay").style.display="none"; document.getElementById("appContainer").classList.add("active"); document.getElementById("userName").innerText="Demo"; renderAll(); renderStocks(); renderMonitorList(); renderNews(); } else alert("Credenciais inválidas"); });
document.getElementById("btnRegisterSubmit")?.addEventListener("click",()=>{ alert("Conta criada! Faça login."); document.querySelector("[data-auth='login']").click(); });
document.querySelectorAll(".auth-tab").forEach(t=>{ t.addEventListener("click",()=>{ document.querySelectorAll(".auth-tab").forEach(tt=>tt.classList.remove("active")); t.classList.add("active"); document.getElementById("loginForm").classList.toggle("active-form",t.dataset.auth==="login"); document.getElementById("registerForm").classList.toggle("active-form",t.dataset.auth==="register"); }); });
document.getElementById("btnLogout")?.addEventListener("click",()=>{ currentUser=null; localStorage.removeItem("financa_current"); document.getElementById("authOverlay").style.display="flex"; document.getElementById("appContainer").classList.remove("active"); });
document.querySelectorAll(".period-btn").forEach(b=>{ b.addEventListener("click",()=>{ document.querySelectorAll(".period-btn").forEach(bb=>bb.classList.remove("active")); b.classList.add("active"); renderBalancete(b.dataset.period); }); });
document.querySelectorAll(".nav-item").forEach(item=>{ item.addEventListener("click",()=>{ const screen=item.dataset.screen; document.querySelectorAll(".nav-item").forEach(n=>n.classList.remove("active")); item.classList.add("active"); document.querySelectorAll(".screen").forEach(s=>s.classList.remove("active-screen")); document.getElementById(`screen-${screen}`).classList.add("active-screen"); if(screen==="investimentos"){ renderStocks(); renderMonitorList(); renderNews(); } if(accessibilityMode) speak(`Abrindo tela de ${screen}`); }); });

const savedTheme = localStorage.getItem('theme'); if(savedTheme === 'dark') document.body.classList.add('dark');
const savedAccess = localStorage.getItem('accessibility'); if(savedAccess === 'true') { accessibilityMode = true; document.body.classList.add('large-text'); speechSynthesisEnabled = true; }
const savedUserAuth = localStorage.getItem("financa_current"); if(savedUserAuth){ currentUser=JSON.parse(savedUserAuth); carregarDados(); document.getElementById("authOverlay").style.display="none"; document.getElementById("appContainer").classList.add("active"); document.getElementById("userName").innerText="Demo"; renderAll(); renderStocks(); renderMonitorList(); renderNews(); }